# Generated by Django 3.2 on 2022-07-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220726_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_ad_email',
            field=models.BooleanField(default=False, verbose_name='광고성 이메일 수신동의'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_ad_message',
            field=models.BooleanField(default=False, verbose_name='광고성 메세지 수신동의'),
        ),
    ]
