# Generated by Django 3.2 on 2022-07-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name_plural': '관심상품'},
        ),
    ]
