# Generated by Django 3.2 on 2022-08-11 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '스타일'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='users',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='postps', to='users.user'),
            preserve_default=False,
        ),
    ]
