# Generated by Django 3.2 on 2022-08-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '스타일'},
        ),
    ]
