# Generated by Django 3.2 on 2022-07-28 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '브랜드'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': '사진'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['eng_name', 'updated'], 'verbose_name_plural': '상품'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='브랜드명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=120, verbose_name='색상'),
        ),
        migrations.AlterField(
            model_name='product',
            name='eng_name',
            field=models.CharField(max_length=150, verbose_name='영어 이름'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kor_name',
            field=models.CharField(max_length=150, verbose_name='한글 이름'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(max_length=80, verbose_name='모델 번호'),
        ),
        migrations.AlterField(
            model_name='product',
            name='released',
            field=models.DateField(verbose_name='발매일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='released_price',
            field=models.PositiveIntegerField(verbose_name='발매가'),
        ),
    ]
